kind: Service
apiVersion: v1
metadata:
  name: NAMESPACE
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: NAMESPACE
status:
  loadBalancer: {}
