kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    description: Defines how to deploy the joke application
  name: jokesite
  labels:
    app: jokesite
spec:
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - jokesite
        from:
          kind: ImageStreamTag
          namespace: jokesite
          name: 'jokesite:latest'
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    name: jokesite
    deploymentconfig: jokesite
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: jokesite
        name: jokesite
    spec:
      containers:
        - name: jokesite
          image: >-
            quay.io/bicycleboy/jokesite:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_SERVICE_NAME
              value: postgresql
            - name: DATABASE_ENGINE
              value: postgresql
            - name: DATABASE_NAME
              value: jokedb
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: jokesite
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jokesite
                  key: database-password
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jokesite
                  key: django-secret-key              
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      initContainers:
        - name: jokesite-init-postgresql
          image: busybox
          command: ['sh', '-c', 'sleep 10']     
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
