kind: Secret
apiVersion: v1
metadata:
  name: jokesite
  namespace: jokesite
  labels:
    app: jokesite
data:
  database-password: L3orJTxDYVduNElFaXY=
  database-user: flxBQUAoZnwxMSds
  django-secret-key: PUhbbzR0JG9qbEl+clA0eHRdQj4+QzEn
type: Opaque
