kind: Secret
apiVersion: v1
metadata:
  name: jokesite
  namespace: jokesite
  labels:
    app: jokesite
data:
  database-password: STI1b0JLJUtKaTh+Z2g=
  database-user: ZEFDXXhReFJqQjNy
  django-secret-key: OChFWSp3UWdOWi15ZHYyKkI3W1VSdCZ6
type: Opaque
