kind: Secret
apiVersion: v1
metadata:
  name: jokesite
  namespace: jokesite
  labels:
    app: jokesite
data:
  database-password: QjUwdC42WU8/PWpFQGw=
  database-user: YFQ+Nj8mY05jNHdR
  django-secret-key: LFEvS2RtRXQibyFkZHZkOz44Mzcxfndt
type: Opaque
