kind: Service
apiVersion: v1
metadata:
  name: jokesite
  labels: 
    app: jokesite 
  annotations:
    description: Exposes and load balances the application pods
    service.alpha.openshift.io/dependencies: '[{"name": "postgresql", "kind": "Service"}]'
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jokesite
    deploymentconfig: jokesite